### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by jnr4817** [asherao/KIO-WA#2]
Noticed when messing with alt adjustment baro vs radalt and setting different levels 50-10000, the ai gets confused base on current alt and agl vs msl when using either setting. For example, took off at 2200 feet msl, went to 10000ft. then returned to 1000 in rdralt mode and aircraft flew direct into ground. It is like the ai did not even use rdralt mode and continued in baro mode. easy to reproduce.

**Comment by blueberrypi-studio** [comment]
This may be an issue with the KW also, have you tried it with just the keybinds?

**Comment by jnr4817** [comment]
Not yet. I'll report back when I do.

**Comment by jnr4817** [comment]
Appears that the oem AI pilot is having issues when using baro vs rdralt setting. The ai gets confused when swapping between modes based on current altimeter.

**Comment by asherao** [comment]
Not a problem with KIO-WA, got it. Thank you.
